### ISSUE TITLE
chown error at end of build process

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/openocd-build#1]
Hi Liviu - not a big deal but just FYI...

I just pulled the latest openocd build script and ran a --win32 build.
At the end of build process I get this:

```
EXE header size:               86528 / 75776 bytes
Install code:                          (87870 bytes)
Install data:                          (6055626 bytes)
Uninstall code+data:                   (93135 bytes)
Compressed data:             2256539 / 6236631 bytes
CRC (0x29E1DA20):                  4 / 4 bytes

Total size:                  2343071 / 6312411 bytes (37.1%)
/Host/Work/openocd/deploy /tmp/build/win32
SHA: 4b38f8259fdb12e85877593c634ea66aa9b865bd184e3843a9bb9ac61fdfcc18 ?gnu-mcu-eclipse-openocd-0.10.0-4-20171013-1627-dev-win32-setup.exe
/tmp/build/win32

Changing owner to non-root Linux user...
chown: cannot access '/Host/Work/openocd/install': No such file or directory
```

I presume that ideally the chown error should not occur?

In case it matters I'm doing this on a Ubuntu 16.04 64 bit VM.

Hope this helps.

**Comment by TommyMurphyTM1234** [comment]
FWIW it also happens on a --deb32 build.

```
Creating tgz archive...

/Host/Work/openocd/deploy /tmp/install/debian32/archive
SHA: c562f8a2ccee3923283851716bb2843c02052f484080a7f330182b992511aefb ?gnu-mcu-eclipse-openocd-0.10.0-4-20171013-1645-dev-debian32.tgz
/tmp/install/debian32/archive

Changing owner to non-root Linux user...
chown: cannot access '/Host/Work/openocd/install': No such file or directory
```

**Comment by ilg-ul** [comment]
hmm... I did an openocd build recently, I don't remember seeing this. perhaps it is linux specific.

I'll investigate.

**Comment by ilg-ul** [comment]
it was linux specific. it was related to moving the install folder to internal docker folder, not updated for the chown patch.

since I do not have the environment to run full linux builds, could you check if it works for you?

be sure you update the build script and the helper.

**Comment by TommyMurphyTM1234** [comment]
No longer an issue with the latest build scripts.
