### ISSUE TITLE
Patch update

### ISSUE THREAD

**Issue by praveents** [gnu-mcu-eclipse/openocd-build#10]
Want to update the patch http://openocd.zylin.com/#/c/4321/ for qspi nor flash debugging and programming.

I have followed the steps mentioned in the below links to build openocd.

https://github.com/gnu-mcu-eclipse/openocd
https://gnu-mcu-eclipse.github.io/openocd/build-procedure/

Now, how do I apply the patch and build for win64 system?

Thanks,
Praveen

**Comment by ilg-ul** [comment]
I think that the easiest way is to simply apply the patch to the local git, remove everything else and rerun the build.
