### ISSUE TITLE
Missing source-package

### ISSUE THREAD

**Issue by cmorty** [gnu-mcu-eclipse/openocd-build#11]
While OpenOCD is built for quite a few platforms, a source package is missing. The source-Package provided by github upon release misses the submodules. Also autotools and co are still needed to build. Running `make dist` on any of the targets and uploading `*.tar.gz2` _should_ do the job*. That tar.bz2 can then be built with `./configure && make`

* I'm not to familiar with autotools, but as far as I understood the docs, this does the job and worked for me (using msys and a Galileo board).

**Comment by ilg-ul** [comment]
can you be more specific? what 'source-Package' are you talking about? and where is it used?

the build is quite complex, and passes on all platforms.

FYI, this project is currently under migration to https://github.com/xpack-dev-tools/openocd-xpack.

**Comment by cmorty** [comment]
`make dist` creates a tar with all files necessary to build your software, yet without the dependencies on autotools and co. Consequently you could also do the following:
* `./bootstrap`
* `./configure`
* `make dist`
* Use the generated tar as input to any other platforms (without autotools installed) and just run
* `./configure && make`
This saves you from having to install autotools on the build target (as in my case, where the yocto-image has no autotools).

**Comment by ilg-ul** [comment]
ah, that's a different use case.

if you have a proposal on how to improve the build scripts, please contribute it to the new repository, but personally I'm not sure that this approach is realistic, given the source dependencies, that need also be compiled.

**Comment by cmorty** [comment]
.... `make dist` takes care of the dependencies. It automatically includes the code from  the `git2cl`, `jimtc` and `libjaylink` submodules into the tar.

**Comment by ilg-ul** [comment]
the build requires many other libraries compiled from separate sources (libusb, libftdi, libiconv, hidapi), does it include them too?

**Comment by cmorty** [comment]
`make dist` only packs the files needed to build/compile the code. Thus required libraries are not part of the tar, as they are not built, but only linked against. And packaging them would be dangerous, as the headers must fit to the installed libraries. The `./configure` magic however checks whether they are available and in the right version. 
Thus no, `make dist` only frees you from having to checkout using git and running `./bootstrap`. The rest is still necessary.

**Comment by cmorty** [comment]
Yet basically what I'm wishing for: Run `make dist` additionally to `make` on any platform and provide the generated `.tar.bz2` as download.

**Comment by ilg-ul** [comment]
I'm afraid you missed the point of this distribution, which is 

- binary
- completely standalone 

thus it packs all libraries together with the executable; you don't need anything else installed on your machine, and definitelly you do not want to recompile everything.

if you want changes in the make files, you probably want to address them to the upstream project, I'm using them as-is.

**Comment by cmorty** [comment]
Somehow I have the feeling we talk/write past each other: I don't want _any_ changes. I just wish for a platform-neutral source-Package without the dependencies (additionally to the self-contained binary packages), as the official OpenOCD seems to make no releases any more. It's all there: OpenOCD's automake already takes care of everything. It's just an additional call to `make` during the build process.

**Comment by ilg-ul** [comment]
I'm still strugling to understand your message.

did you run the build scripts as they are now? do you suggest to insert a new line in them? where? could you experiment with this process yourself and come with a concrete proposal?

**Comment by cmorty** [comment]
No, I didn't run your code. So basically the Idea is something like this: https://github.com/cmorty/openocd-xpack/commit/b0723ec4bf60ce4dcc2b5088c1d09dbe0fe1ed08
This will create a .tar.bz2. The contents of that file would be the source release. It will only contain the code to build openocd, but not the libraries it depends on.
But I do understand that this might not be in your focus. It would just be nice to have source releases, too.

**Comment by ilg-ul** [comment]
I retain the idea to have source releases that match the binary releases, but I don't know yet how to address them, since in my opinion the archive should include not only openocd, but the dependencies too. 

The problem is even more general, since it probably applies to all binary packages, not only openocd.

If we can further clarify the use case, perhaps we can come with a solution.

I suggest we move the discussion to https://www.tapatalk.com/groups/xpack/general-dev-tools-discussions-f28/

The first thing to clarify is the exact purpose of the source distribution; apart from archiving purposes, in other words having in a single place all the source code used in a release, what would be the use case? how would be such a source release be used?

**Comment by cmorty** [comment]
Other libs:
As far as I can see they all use autotools (run `configure`). Thus they all support `make dist`. After building all of them you just need to collect all the generated `.tar.bz2`

As for the usecase: Being able to compile on any platform without a binary package and without having to install more dependencies than really necessary (ideally not more than `make` and `gcc`).

**Comment by ilg-ul** [comment]
https://www.tapatalk.com/groups/xpack/proposal-create-source-packages-t4.html
