### ISSUE TITLE
add support for native build on Linux

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/openocd-build#2]
Since the binaries might not run on some older distributions, It would be useful to build on Linux without Docker, using the local system libraries.

For the build to pass, the build tools should be available (they are tested, and if not present, the script stops).

**Comment by ilg-ul** [comment]
done. 

to run a native build, **do not** specify any --xxx platform option.

**Comment by ilg-ul** [comment]
@TM1234, could you try a native build on your linux?

**Comment by TommyMurphyTM1234** [comment]
Works fine now for --win32 and --deb32:

--win32

```
Changing owner to non-root Linux user...

Checking openocd...

DLLs:
	DLL Name: libusb0.dll
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: SETUPAPI.dll
	DLL Name: USER32.dll
	DLL Name: WS2_32.dll

Build completed.

Distribution file /Host/Work/openocd/deploy/gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1413-dev-win32-setup.exe created.
-rw-r--r-- 1 1000 1000 2342586 Oct 14 14:21 /Host/Work/openocd/deploy/gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1413-dev-win32-setup.exe

Script "build.sh" completed.
openocd-win32-build
do_host_build_target  completed

a5d5dfeddcbd094ebc71cfe544f8901f69adf859dbaa8d4d394d1c918f22b690 ?gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1413-dev-win32-setup.exe
f5c06ffe94111250764fdd97c051e067d616e2b324ef3b556e9f96e26788514e ?gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1413-dev-win32.zip

Script "/home/user/Downloads/openocd-build.git/scripts/build.sh" completed at Sat Oct 14 15:21:14 IST 2017.
Duration: 7 minutes.
```

--deb32

```
GNU MCU Eclipse 32-bits Open On-Chip Debugger 0.10.0+dev-00218-gda43038f (2017-10-14-14:24)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

Build completed.

Distribution file /Host/Work/openocd/deploy/gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1423-dev-debian32.tgz created.
-rw-r--r-- 1 1000 1000 2819705 Oct 14 14:27 /Host/Work/openocd/deploy/gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1423-dev-debian32.tgz

Script "build.sh" completed.
openocd-debian32-build
do_host_build_target  completed

a5d5dfeddcbd094ebc71cfe544f8901f69adf859dbaa8d4d394d1c918f22b690 ?gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1413-dev-win32-setup.exe
f5c06ffe94111250764fdd97c051e067d616e2b324ef3b556e9f96e26788514e ?gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1413-dev-win32.zip
b3c2df9118a6db2a846c873506ac3552cb19aba138e4573614a4de9a64497ec4 ?gnu-mcu-eclipse-openocd-0.10.0-4-20171014-1423-dev-debian32.tgz

Script "/home/user/Downloads/openocd-build.git/scripts/build.sh" completed at Sat Oct 14 15:27:48 IST 2017.
Duration: 4 minutes.
```

But if I don't specify any platform option I get this:

```
user@ubuntu-16:~$ bash ~/Downloads/openocd-build.git/scripts/build.sh

Work folder: "/home/user/Work/openocd".
Helper script: "/home/user/Downloads/openocd-build.git/scripts/helper/build-helper.sh".
Script "/home/user/Downloads/openocd-build.git/scripts/build.sh" started at Sat Oct 14 15:40:58 IST 2017.

Running on Ubuntu 64-bits.

Checking host curl...
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3

Checking host git...
git version 2.7.4

Checking host automake...
automake (GNU automake) 1.15

Checking host patch...
GNU patch 2.7.5

Checking host tar...
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

Checking host unzip...
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
Copying openocd-build.git from Downloads...
Cloning into '/home/user/Work/openocd/openocd-build.git'...
done.

================================================================================
Creating the native distribution...
Unsupported host Ubuntu, exit.
```

**Comment by ilg-ul** [comment]
> Unsupported host Ubuntu, exit.

yes, I noticed, I'm working on a fix.

**Comment by TommyMurphyTM1234** [comment]
Not sure if you're still in the middle of fixing it but I pulled the stuff anew just now and when I do a native build I get this:

```
Creating the native distribution...

Running "build.sh" script locally...

Linux ubuntu-16 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Checking automake...
automake (GNU automake) 1.15
Checking cmake...
/home/user/Work/openocd/scripts/build.sh: line 155: cmake: command not found

```

I installed cmake and tried again and I get this:

```
Running libusb1 configure...
/home/user/Work/openocd/scripts/build.sh: line 228: target_bits: unbound variable
```

**Comment by ilg-ul** [comment]
> target_bits: unbound variable

yes, there are many such small fixes required, I'm working on them one by one.

**Comment by TommyMurphyTM1234** [comment]
OK - apologies for being too trigger happy. :-) 
I'll wait for an update from you on this.

**Comment by ilg-ul** [comment]
it was more complicated than expected. the trick was to reliably get the identity of the actual build environment, native or container.

commit https://github.com/gnu-mcu-eclipse/openocd-build/commit/b3b89f3c414e893a8d5eb7cbba9d2b2deb81c5e3 passed the build on macOS with `--all`, on macOS as native and on Ubuntu as native.

**Comment by TommyMurphyTM1234** [comment]
Hi Liviu - is there still a problem with the native build?
I installed a clean Ubuntu 16.04 64 bit VM, installed the following packages one at a time each time the build failed looking for something:

`sudo apt-get install git curl automake libtool cmake patchelf libudev-dev 
`

but the build still failed as follows because, it seems, that the openocd bootstrap process was not run before attempting to run configure:

```
----------------------------------------------------------------------
Libraries have been installed in:
   /home/user/Work/openocd/install/ubuntu64/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/user/Work/openocd/install/ubuntu64/include/hidapi'
 /usr/bin/install -c -m 644 ../hidapi/hidapi.h '/home/user/Work/openocd/install/ubuntu64/include/hidapi'
make[2]: Leaving directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1/libusb'
make[1]: Leaving directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1/libusb'
Making install in hidtest
make[1]: Entering directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1/hidtest'
make[2]: Entering directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1/hidtest'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1/hidtest'
make[1]: Leaving directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1/hidtest'
make[1]: Entering directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1'
make[2]: Entering directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/user/Work/openocd/install/ubuntu64/share/doc/hidapi'
 /usr/bin/install -c -m 644 README.txt AUTHORS.txt LICENSE-bsd.txt LICENSE-gpl3.txt LICENSE-orig.txt LICENSE.txt '/home/user/Work/openocd/install/ubuntu64/share/doc/hidapi'
 /bin/mkdir -p '/home/user/Work/openocd/install/ubuntu64/lib/pkgconfig'
 /usr/bin/install -c -m 644 pc/hidapi-hidraw.pc pc/hidapi-libusb.pc '/home/user/Work/openocd/install/ubuntu64/lib/pkgconfig'
make[2]: Leaving directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1'
make[1]: Leaving directory '/home/user/Work/openocd/build/ubuntu64/hidapi-hidapi-0.8.0-rc1'

Running OpenOCD configure...
bash: /home/user/Work/openocd/openocd.git/configure: No such file or directory
user@ubuntu-16:~$ 

```

**Comment by TommyMurphyTM1234** [comment]
Actually a --win32 build also fails because bootstrap is not getting called.

```
Running libhid make...
i686-w64-mingw32-gcc -I../hidapi -g -c hid.c -o hid.o
ar: creating libhid.a
'libhid.a' -> '/tmp/install/win32/lib/libhid.a'
'/Host/Work/openocd/hidapi-hidapi-0.8.0-rc1/hidapi/hidapi.h' -> '/tmp/install/win32/include/hidapi/hidapi.h'

Running OpenOCD configure...
bash: /Host/Work/openocd/openocd.git/configure: No such file or directory
user@ubuntu-16:~$ 

```

**Comment by ilg-ul** [comment]
Bootstrap is called only after clone. If it failed, you need to cleanall and retry.

**Comment by ilg-ul** [comment]
But from your repeated question I retain the proposal to improve the mechanism to automatically retry bootstrap until configure is present.

**Comment by TommyMurphyTM1234** [comment]
Odd - I tried again after manually deleting the ~/Work and ~/Download/openocd-build.git folders and then git cloning anew and it worked for native and --win32 and --deb32. I'm not sure what happened earlier for it to fail. Maybe one of the initial attempts that failed due to missing packages left things in an anomalous state that caused bootstrap to fail or be skipped?

**Comment by TommyMurphyTM1234** [comment]
OK - just to clarify:



- I started with a new/clean Ubuntu 16.04 64 VM - base desktop install + any available updates

- I installed Docker as per the instructions here: https://gnu-mcu-eclipse.github.io/developer/build-binaries-prerequisites/

- I installed the following packages

`sudo apt-get install git curl automake libtool cmake patchelf libudev-dev texinfo texlive `

- I cloned the repo as per the instructions here: https://gnu-mcu-eclipse.github.io/openocd/build-procedure/

- I ran a native build: bash and it worked successfully.

```
~/Downloads/openocd-build.git/scripts/build.sh

...

Script "/home/user/Downloads/openocd-build.git/scripts/build.sh" completed at Sun Oct 15 14:56:54 IST 2017.
Duration: 5 minutes.

```

**Comment by ilg-ul** [comment]
Great!

> bootstrap

You identified a small fault in the bootstrap logic. The script is now executed only after clone. The clone step is not executed if the git folder is already there. If the bootstrap fails due to a missing tool, the only way to recover is via cleanall, to remove the git folder, to force a new clone and a script run.

I'll fix this as soon as I get back to my computer.

**Comment by ilg-ul** [comment]
commit https://github.com/gnu-mcu-eclipse/openocd-build/commit/23d1bb70718358050160e77831b83badccc9aad2 should fix the bootstrap logic.

the script checks for the `configure` file presence; if not there, run bootstrap.

**Comment by ilg-ul** [comment]
FYI, I've just tried the build script on ARCH systems, and... it failed.

As most software problems, there are solutions, but are too complicated to be fixed with a simple patch. 

The main problem is that the build is not creating a static binary, but uses shared libraries. I'm doing my best to build most of these libraries during the build, but there are some that would require more effortts that are reasonable for this case. One of them is libudev, which is a minimalistic library, but is part of systemd. So the solution is to copy the system libudev to the openocd distribution. Unfortunately some systems, like ARCH, have multiple versions of libudev installed, and the script should find exactly the one referenced during the build. The current script does not do this, but take the first that it finds, which is not the right one. 

Building portable binaries is definitely not an easy thing to do, and I think the existing approaches all have problems.

A better solution would be a mechanism like the one I try to create for xPacks, actually inspired from the JavaScript/Node.js ecosystem, where each build is by definition considered local, without any dependencies on the host distribution, and builds exactly the needed versions of all relevant libraries and build tools.

But implementing the full xPack build mechanism will take some time...

**Comment by TommyMurphyTM1234** [comment]
Thanks for the quick turnaround on addressing the other issues Liviu.

> Building portable binaries is definitely not an easy thing to do, 

Agreed! :-(

**Comment by ilg-ul** [comment]
unfortunatelly with the current structure of the build scripts it is very difficult to make it run natively on **any** linux distribution.

preferably the script would generate static executables, but, as far as I remeber, some of the libraries might not be very easy to switch to static.

**Comment by ilg-ul** [comment]
I did some progress in making some of the libraries static, but could not make it fully static :-(

I'm closing this, since a fully portable build script to run natively on any Linux is a very hard thing to achieve.
