### ISSUE TITLE
Minor issue: -lpthread redundant/unnecessary in linux openocd build script?

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/openocd-build#5]
See here:

https://github.com/gnu-mcu-eclipse/openocd-build/blob/master/scripts/build.sh#L1602

When -lpthread is removed from the libs openocd for linux still builds/links fine.
Is -lpthread here redundant?

**Comment by ilg-ul** [comment]
If it builds and runs fine, it is probably redundant.

**Comment by ilg-ul** [comment]
Is the pthread library always present on linux? it might be possible that -lpthread is there to be sure it is included statically, so the binary runs regardless of the presence of the system dynamic library.

**Comment by TommyMurphyTM1234** [comment]
I don't really understand.
If -lpthread is specified then isn't that telling the linker to link the static libpthread.a?
And if -lpthread is removed and openocd still compiles and links and then runs OK doesn't that mean that it's redundant?

**Comment by ilg-ul** [comment]
Please check if the resulting binary, when linked without -lpthread, has a reference to the dynamic version of the library. If it does not, than the option is indeed redundant. If it does, build again with the option and check the binary. The reference to the dynamic library should no longer be there, meaning the static version of library was included in the binary.

**Comment by TommyMurphyTM1234** [comment]
Ok - ignore this.
I was working with an older (and possibly modified) version of the build scripts.
I pulled the latest and started from scratch and now when I remove -lpthread from the openocd part of the script it fails so I guess that it is required:

```
/bin/bash ./libtool  --tag=CC   --mode=link gcc -Wall -Wstrict-prototypes -Wformat-security -Wshadow -ffunction-sections -fdata-sections -m32 -pipe -Wno-format-truncation -Wno-format-overflow  -L/tmp/install/centos32/lib64 -L/tmp/install/centos32/lib -static-libstdc++ -Wl,--gc-sections -o src/openocd src/main.o src/libopenocd.la  ./jimtcl/libjim.a  -ldl -lrt -ludev
libtool: link: gcc -Wall -Wstrict-prototypes -Wformat-security -Wshadow -ffunction-sections -fdata-sections -m32 -pipe -Wno-format-truncation -Wno-format-overflow -static-libstdc++ -Wl,--gc-sections -o src/openocd src/main.o  -L/tmp/install/centos32/lib64 -L/tmp/install/centos32/lib src/.libs/libopenocd.a -lusb -lftdi1 -lhidapi-hidraw -lusb-1.0 -lm ./jimtcl/libjim.a -ldl -lrt -ludev
/opt/xbb/lib/gcc/i686-linux-gnu/7.2.0/../../../../i686-linux-gnu/bin/ld: /tmp/install/centos32/lib/libusb-1.0.a(libusb_1_0_la-linux_udev.o): undefined reference to symbol 'pthread_create@@GLIBC_2.1'
/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2577: src/openocd] Error 1
make[2]: Leaving directory '/tmp/build/centos32/openocd'
make[1]: *** [Makefile:3823: all-recursive] Error 1
make[1]: Leaving directory '/tmp/build/centos32/openocd'
make: *** [Makefile:1643: all] Error 2
```
Originally I was curious because openocd itself is single threaded and does not use pthreads so I didn't understand why it was being referenced at link time.
But I guess that udev (and maybe hidapi?) need it?
Note that openocd's zy1000.c does include pthread.h but the source file doesn't seem to actually use any pthreads calls.

https://github.com/gnu-mcu-eclipse/openocd/blob/gnu-mcu-eclipse-dev/src/jtag/zy1000/zy1000.c#L48

I'll close this issue as irrelevant.
Apologies for the false alarm.
