### ISSUE TITLE
"Unescaped left brace in regex is deprecated" warnings (x2) when building

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/openocd-build#7]
Not sure if this is important or not so I'm erring on the side of caution by logging it.
When I build as follows:

`bash ~/Downloads/openocd-build.git/scripts/build,sh --win64 2>&1 | tee build.log`

I find two instances of this warning (?) in build.log (when configuring jimtcl I think):

`Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /opt/xbb/bin/automake line 3936.`

Perhaps it's simply something inherited from the upstream package (as opposed to being an issue with the GME openocd build scripts) which should be logged there?

**Comment by ilg-ul** [comment]
I guess the problem was fixed, in the latest builds I no longer see this message.
