### ISSUE TITLE
Alternative solution to fix unstable state of the built

### ISSUE THREAD

**Issue by AntonKrug** [gnu-mcu-eclipse/openocd-build#9]
Sometimes it's possible for the build to fail (when experimenting with stuff), but then it will not finish and it will not set the privileges to lower user. To fix this state I have to call clean but that will fail as it has no access to root files.

3 alternatives how to approach this:

1. execute the clean inside container so you will have the root privileges over the mounted volume so it will be able to clean itself from funny state. Didn't test this but it should work.

2. create lower privileged user inside the container mimicking the host user and creating files straight away as the correct user and no need to fix the privileges later and it will be able to clean itself from funny state without any other hacks. Might require changes inside the container to fully support this. But in my smaller scale experiments this can work pretty well.

3. Create very wide umask which then will cause all files to be accessible to by everybody, which means that when docker will create a temporary folder as root you will be still able to delete them as user when the build breaks. This approach should require the least amount of changes, tested it quickly and it works pretty well but with the umask is a bit dangerous. In this usage it shouldn't matter, but it could be abused if not used correctly. I personally prefer the alternative 2 but it requires few changes. While this alternative should be the easiest to implement.

**Comment by AntonKrug** [comment]
Similar (if not the same) approach then could be used with RISC-V build scripts as well:

https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build

**Comment by ilg-ul** [comment]
> I personally prefer the alternative 2

me too (#MeToo?)

**Comment by AntonKrug** [comment]
Sorry, I miss clicked.

**Comment by ilg-ul** [comment]
I added both umask and also experimented with running docker with user credentials.

The second is not yet fully functional, since I noticed differences between macOS and Linux, and had no time to smooth the details; if you can give it a try and make it work on Linux, I can update the scripts to use it.

**Comment by AntonKrug** [comment]
I will give it try and keep you update
